//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public long SaleID { get; set; }
        public long ManagerID { get; set; }
        public long ClientID { get; set; }
        public long ProductID { get; set; }
        public System.DateTime SaleDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Product Product { get; set; }
    }
}
